# Generated by Django 3.1.10 on 2022-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('event_name', models.CharField(max_length=1000)),
                ('font_family', models.CharField(max_length=1000)),
                ('name_x_pos', models.IntegerField(default=0)),
                ('name_y_pos', models.IntegerField(default=0)),
                ('name_box_height', models.IntegerField(default=100)),
                ('name_box_width', models.IntegerField(default=100)),
                ('event_x_pos', models.IntegerField(default=0)),
                ('event_y_pos', models.IntegerField(default=0)),
                ('event_box_height', models.IntegerField(default=100)),
                ('event_box_width', models.IntegerField(default=100)),
            ],
        ),
    ]
