# Generated by Django 3.1.10 on 2022-05-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.CharField(max_length=1000),
        ),
    ]
